### PR TITLE
bump compatible mongoose version

### PR DESCRIPTION
**Pull request by Zugwalt**
In my tests this worked fine with Mongoose 4.1.

We may even want to considering changing the range to:
```
"mongoose": ">= 3.5.0 < 5.0.0"
```

### CODE REVIEW

**Comment by zachizi** [comment]
@leeroybrun might this be merged?

**Comment by leeroybrun** [comment]
Yes sure, sorry for the delay!

**Comment by zachizi** [comment]
thanks!

**Comment by zachizi** [comment]
@leeroybrun could you also publish/tag/release for installing with npm?

**Comment by kuehn-sba** [comment]
take this peerDependency complete out.. it's only anyoing and no one knows when mongoose change next his last stable version which runs compatibel with last stable node. so please let it out....

**Comment by leeroybrun** [comment]
@zachizi Yes sure, sorry for this, I just forgot... The new version is now available.

@kuehn-sba I have no problem to remove the peerDependency, it came from the previous project from where I forked from, and yes it's quite annoying... What do others think about this?

**Comment by leeroybrun** [comment]
Ok, for now I've removed the max version of mongoose from peer dependencies.

If someone think it's not a great idea or if we encounter some problems, we can put it back.

Thanks

**Comment by zachizi** [comment]
@leeroybrun no worries, thanks for publishing!

**Pull request merged**
